### ISSUE TITLE
[리팩터링] 중복 코드 수정

### ISSUE THREAD

**Issue by leeeeeoy** [malmo-malmo/momo-server#127]
> 우측의 Assignees, Labels, Project를 상황에 맞게 선택해주세요 😊

## 상세 내용
* 중복 코드 수정 및 공통 컴포넌트 묶기

## 진행 현황
- [x] 일정 카드 수정
- [x] 카테고리 아이콘 수정
- [x] 홈 화면 그룹 카드 수정
- [x] 앱 바 수정
- [x] 데이트 포맷 파일 분리

**Comment by highright96** [comment]
멋지십니다
