### ISSUE TITLE
[수정] 클라이언트 요청사항 (12/5)

### ISSUE THREAD

**Issue by leeeeeoy** [malmo-malmo/momo-server#140]
> 우측의 Assignees, Labels, Project를 상황에 맞게 선택해주세요 😊

## 버그 사항
* 테스트 데이터가 안 섞여서 오는 것 같습니다. 코드 상에서는 섞으신 것 같은데 원인을 모르겠네요ㅎㅎ 나중에 한 번 확인해주세요!

## 원하는 상황
* 날짜, 학교 그리고 카테고리 다 섞어주시면 좋을 것 같습니다
## 스크린샷
![image](https://user-images.githubusercontent.com/63850050/144732466-41ffe615-23de-4388-a652-72da5864abf3.png)

**Comment by highright96** [comment]
알겠습니다. 변경하고 말씀드릴께요~

**Comment by highright96** [comment]
확인해보니 모임 시작 날짜가 동일한 것 같더라고요. 그래서 랜덤한 날짜로 입력되도록 변경했습니다.

![image](https://user-images.githubusercontent.com/55661631/144734834-b62059be-f563-41b2-8022-aa0f4d73cbe5.png)

학교와 카테고리는 위 스크린샷에 보이는데로 섞여서 들어가는걸로 확인되는데, 어느 부분이 문제이신걸까요?

일단 변경한 부분은 푸시했습니다. 확인 부탁드릴께요!

**Comment by leeeeeoy** [comment]
![image](https://user-images.githubusercontent.com/63850050/144742272-02991d99-da14-4fcc-859d-9443cfa822e4.png)
받아서 했는데 주변더보기랑 학교더보기 응답은 아까랑 똑같네요 어디선가 꼬인듯한...ㅠㅜ
시작 날짜는 수정됐습니다!


![image](https://user-images.githubusercontent.com/63850050/144742304-7ed00f25-ad98-4cf0-b7eb-7bfb3ff8f607.png)
그리고 모임을 생성해서 다시 홈화면에서 조회를 해봤는데 생성한 모임이 아니라 다른 모임이 넘어오는 것 같습니다



![image](https://user-images.githubusercontent.com/63850050/144742324-d4f0ff15-dcb0-423f-93b4-681fefaf7b50.png)
모임 생성 후 모임 요청 응답 데이터



문서대로 요청 응답은 잘 오는데 아마 테스트 데이터라서 어디선가 꼬인게 아닌가 싶습니다! 일단은 다른 API들 더 테스트 해보겠습니다.



'
'
'
'
'

[수정] 요청 페이지가 1이 아니라 0부터였네요...죄송합니다 ㅎㅎ 다 잘 넘어오네요
